/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    patients: Patient;
    appointments: Appointment;
    visits: Visit;
    invoices: Invoice;
    auditLogs: AuditLog;
    'medical-documents': MedicalDocument;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    patients: PatientsSelect<false> | PatientsSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    visits: VisitsSelect<false> | VisitsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    auditLogs: AuditLogsSelect<false> | AuditLogsSelect<true>;
    'medical-documents': MedicalDocumentsSelect<false> | MedicalDocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  /**
   * Auto-generated from the name; used for public URLs later.
   */
  slug?: string | null;
  phone: string;
  address?: string | null;
  city?: string | null;
  district?: string | null;
  state?: string | null;
  /**
   * Clinic photo URL from Google Places or listing.
   */
  photoUrl?: string | null;
  country?: string | null;
  status: 'pending' | 'active' | 'suspended';
  /**
   * Subscription tier; limits enforced in code (src/lib/plans.ts).
   */
  plan: 'free' | 'clinic' | 'plus';
  upgradeRequest?: {
    requestedPlan?: ('free' | 'clinic' | 'plus') | null;
    requestedAt?: string | null;
    note?: string | null;
  };
  /**
   * How this clinic was created — for analytics.
   */
  onboardingSource: 'self-serve' | 'manual';
  settings: {
    appointmentDurationMins: number;
    openTime: string;
    closeTime: string;
    /**
     * Market-agnostic core — all amounts are formatted from this.
     */
    currency: 'INR' | 'PKR' | 'USD' | 'GBP' | 'AED' | 'SAR';
    /**
     * All times are displayed in this timezone.
     */
    timezone: 'Asia/Kolkata' | 'Asia/Karachi' | 'Asia/Dubai' | 'Asia/Riyadh' | 'Europe/London' | 'America/New_York';
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'superAdmin' | 'owner' | 'doctor' | 'receptionist' | 'patient';
  /**
   * Required for all roles except super admin.
   */
  tenant?: (string | null) | Tenant;
  /**
   * Linked patient record for patient portal accounts.
   */
  patientProfile?: (string | null) | Patient;
  phone?: string | null;
  /**
   * Profile photo URL from Google or professional registry.
   */
  photoUrl?: string | null;
  active?: boolean | null;
  emailVerified?: boolean | null;
  verifyTokenHash?: string | null;
  verifyTokenExp?: string | null;
  qualification?: string | null;
  specialty?: string | null;
  medicalRegistrationNumber?: string | null;
  stateMedicalCouncil?: string | null;
  /**
   * In the clinic currency. Used by billing (v2).
   */
  consultationFee?: number | null;
  availabilityType?: ('regular' | 'onCall' | 'byAppointment') | null;
  /**
   * Days this doctor sees patients (daily = all; alternate = e.g. Mon/Wed/Fri; weekly = one).
   */
  availableDays?: ('sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat')[] | null;
  availableFrom?: string | null;
  availableTo?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients".
 */
export interface Patient {
  id: string;
  tenant: string | Tenant;
  /**
   * Auto-assigned per clinic.
   */
  mrn?: string | null;
  name: string;
  phone: string;
  gender: 'male' | 'female' | 'other';
  dateOfBirth?: string | null;
  ageYears?: number | null;
  bloodGroup?: ('A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-') | null;
  /**
   * Shown prominently on the patient profile (safety).
   */
  allergies?: string | null;
  /**
   * 6-digit activation code issued to claim portal account.
   */
  activationCode?: string | null;
  activationTokenHash?: string | null;
  activationTokenExp?: string | null;
  activationAttempts?: number | null;
  addressLine?: string | null;
  city?: string | null;
  district?: string | null;
  state?:
    | (
        | 'Andhra Pradesh'
        | 'Arunachal Pradesh'
        | 'Assam'
        | 'Bihar'
        | 'Chhattisgarh'
        | 'Goa'
        | 'Gujarat'
        | 'Haryana'
        | 'Himachal Pradesh'
        | 'Jharkhand'
        | 'Karnataka'
        | 'Kerala'
        | 'Madhya Pradesh'
        | 'Maharashtra'
        | 'Manipur'
        | 'Meghalaya'
        | 'Mizoram'
        | 'Nagaland'
        | 'Odisha'
        | 'Punjab'
        | 'Rajasthan'
        | 'Sikkim'
        | 'Tamil Nadu'
        | 'Telangana'
        | 'Tripura'
        | 'Uttar Pradesh'
        | 'Uttarakhand'
        | 'West Bengal'
        | 'Delhi'
        | 'Jammu and Kashmir'
        | 'Ladakh'
        | 'Puducherry'
      )
    | null;
  pinCode?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  tenant: string | Tenant;
  patient: string | Patient;
  doctor: string | User;
  start: string;
  durationMins: number;
  end?: string | null;
  reason?: string | null;
  status: 'scheduled' | 'checked-in' | 'completed' | 'cancelled' | 'no-show';
  isWalkIn?: boolean | null;
  /**
   * Auto-assigned per clinic per day for walk-ins.
   */
  tokenNumber?: string | null;
  tokenDay?: string | null;
  cancellationReason?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits".
 */
export interface Visit {
  id: string;
  tenant: string | Tenant;
  appointment: string | Appointment;
  patient: string | Patient;
  doctor: string | User;
  visitDate: string;
  symptoms?: string | null;
  diagnosis?: string | null;
  /**
   * Visible to all clinic staff.
   */
  notes?: string | null;
  vitals?: {
    bpSystolic?: number | null;
    bpDiastolic?: number | null;
    temperatureC?: number | null;
    weightKg?: number | null;
    pulse?: number | null;
  };
  prescription?:
    | {
        medicine: string;
        dosage?: string | null;
        frequency?: ('od' | 'bd' | 'tds' | 'qid' | 'sos' | 'other') | null;
        frequencyNote?: string | null;
        durationDays?: number | null;
        instructions?: string | null;
        id?: string | null;
      }[]
    | null;
  followUpDate?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: string;
  tenant: string | Tenant;
  /**
   * Auto-assigned per clinic (INV-0001).
   */
  invoiceNumber?: string | null;
  visit?: (string | null) | Visit;
  patient: string | Patient;
  /**
   * Snapshotted from the clinic at create time.
   */
  currency?: string | null;
  lineItems: {
    description: string;
    quantity: number;
    unitAmount: number;
    /**
     * quantity × unit amount.
     */
    amount?: number | null;
    id?: string | null;
  }[];
  totalAmount?: number | null;
  payments?:
    | {
        amount: number;
        method: 'cash' | 'card' | 'bank-transfer' | 'other';
        receivedAt?: string | null;
        receivedBy?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  amountPaid?: number | null;
  balanceDue?: number | null;
  paymentStatus?: ('unpaid' | 'partial' | 'paid') | null;
  voided?: boolean | null;
  voidReason?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs".
 */
export interface AuditLog {
  id: string;
  tenant: string | Tenant;
  user: string | User;
  action:
    | 'appointment.created'
    | 'appointment.cancelled'
    | 'appointment.status-changed'
    | 'invoice.voided'
    | 'payment.recorded'
    | 'user.created'
    | 'user.deactivated'
    | 'user.role-changed'
    | 'settings.updated'
    | 'tenant.suspended'
    | 'tenant.reactivated'
    | 'plan.upgrade-requested'
    | 'plan.upgrade-rejected'
    | 'plan.changed'
    | 'export.generated'
    | 'document.uploaded'
    | 'document.updated'
    | 'visit.created'
    | 'visit.updated';
  targetCollection: string;
  targetId: string;
  /**
   * Human-readable, e.g. "Cancelled Bilal Ahmed's 5:30 pm appointment".
   */
  summary: string;
  /**
   * Small structured context (old/new role, amount…). Never a full doc snapshot.
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-documents".
 */
export interface MedicalDocument {
  id: string;
  tenant: string | Tenant;
  patient: string | Patient;
  doctor?: (string | null) | User;
  visit?: (string | null) | Visit;
  appointment?: (string | null) | Appointment;
  uploadedBy: string | User;
  documentType:
    | 'LAB_REPORT'
    | 'BLOOD_TEST'
    | 'URINE_TEST'
    | 'X_RAY'
    | 'CT_SCAN'
    | 'MRI'
    | 'ULTRASOUND'
    | 'ECG'
    | 'PRESCRIPTION'
    | 'REFERRAL'
    | 'DISCHARGE_SUMMARY'
    | 'MEDICAL_CERTIFICATE'
    | 'SCANNED_DOCUMENT'
    | 'IMAGE'
    | 'OTHER';
  title: string;
  description?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  documentDate: string;
  /**
   * SHA-256 hash for integrity and duplicate detection.
   */
  checksum?: string | null;
  status: 'active' | 'archived';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'patients';
        value: string | Patient;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'visits';
        value: string | Visit;
      } | null)
    | ({
        relationTo: 'invoices';
        value: string | Invoice;
      } | null)
    | ({
        relationTo: 'auditLogs';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'medical-documents';
        value: string | MedicalDocument;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  phone?: T;
  address?: T;
  city?: T;
  district?: T;
  state?: T;
  photoUrl?: T;
  country?: T;
  status?: T;
  plan?: T;
  upgradeRequest?:
    | T
    | {
        requestedPlan?: T;
        requestedAt?: T;
        note?: T;
      };
  onboardingSource?: T;
  settings?:
    | T
    | {
        appointmentDurationMins?: T;
        openTime?: T;
        closeTime?: T;
        currency?: T;
        timezone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenant?: T;
  patientProfile?: T;
  phone?: T;
  photoUrl?: T;
  active?: T;
  emailVerified?: T;
  verifyTokenHash?: T;
  verifyTokenExp?: T;
  qualification?: T;
  specialty?: T;
  medicalRegistrationNumber?: T;
  stateMedicalCouncil?: T;
  consultationFee?: T;
  availabilityType?: T;
  availableDays?: T;
  availableFrom?: T;
  availableTo?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients_select".
 */
export interface PatientsSelect<T extends boolean = true> {
  tenant?: T;
  mrn?: T;
  name?: T;
  phone?: T;
  gender?: T;
  dateOfBirth?: T;
  ageYears?: T;
  bloodGroup?: T;
  allergies?: T;
  activationCode?: T;
  activationTokenHash?: T;
  activationTokenExp?: T;
  activationAttempts?: T;
  addressLine?: T;
  city?: T;
  district?: T;
  state?: T;
  pinCode?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  tenant?: T;
  patient?: T;
  doctor?: T;
  start?: T;
  durationMins?: T;
  end?: T;
  reason?: T;
  status?: T;
  isWalkIn?: T;
  tokenNumber?: T;
  tokenDay?: T;
  cancellationReason?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits_select".
 */
export interface VisitsSelect<T extends boolean = true> {
  tenant?: T;
  appointment?: T;
  patient?: T;
  doctor?: T;
  visitDate?: T;
  symptoms?: T;
  diagnosis?: T;
  notes?: T;
  vitals?:
    | T
    | {
        bpSystolic?: T;
        bpDiastolic?: T;
        temperatureC?: T;
        weightKg?: T;
        pulse?: T;
      };
  prescription?:
    | T
    | {
        medicine?: T;
        dosage?: T;
        frequency?: T;
        frequencyNote?: T;
        durationDays?: T;
        instructions?: T;
        id?: T;
      };
  followUpDate?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  tenant?: T;
  invoiceNumber?: T;
  visit?: T;
  patient?: T;
  currency?: T;
  lineItems?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitAmount?: T;
        amount?: T;
        id?: T;
      };
  totalAmount?: T;
  payments?:
    | T
    | {
        amount?: T;
        method?: T;
        receivedAt?: T;
        receivedBy?: T;
        id?: T;
      };
  amountPaid?: T;
  balanceDue?: T;
  paymentStatus?: T;
  voided?: T;
  voidReason?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  action?: T;
  targetCollection?: T;
  targetId?: T;
  summary?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-documents_select".
 */
export interface MedicalDocumentsSelect<T extends boolean = true> {
  tenant?: T;
  patient?: T;
  doctor?: T;
  visit?: T;
  appointment?: T;
  uploadedBy?: T;
  documentType?: T;
  title?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  documentDate?: T;
  checksum?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}